//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDW_COPY_vHIERARCHY_CURR_SEC_ALL_LEVELS
    {
        public int vp_hier_id { get; set; }
        public string vp_cd { get; set; }
        public string vp_level_name { get; set; }
        public string vp_resp_name { get; set; }
        public string vp_resp_title { get; set; }
        public string vp_resp_emp_no { get; set; }
        public Nullable<int> vp_resp_company_cd { get; set; }
        public int org_hier_id { get; set; }
        public string org_cd { get; set; }
        public string org_level_name { get; set; }
        public string org_resp_name { get; set; }
        public string org_resp_title { get; set; }
        public string org_resp_emp_no { get; set; }
        public Nullable<int> org_resp_company_cd { get; set; }
        public int dept_hier_id { get; set; }
        public string dept_cd { get; set; }
        public string dept_level_name { get; set; }
        public string dept_resp_name { get; set; }
        public string dept_resp_title { get; set; }
        public string dept_resp_emp_no { get; set; }
        public Nullable<int> dept_resp_company_cd { get; set; }
        public int sect_hier_id { get; set; }
        public string sect_cd { get; set; }
        public string sect_level_name { get; set; }
        public string sect_resp_name { get; set; }
        public string sect_resp_title { get; set; }
        public string sect_resp_emp_no { get; set; }
        public Nullable<int> sect_resp_company_cd { get; set; }
        public Nullable<System.DateTime> Last_Updt_Ts { get; set; }
        public string Last_Updt_Usr_Id { get; set; }
        public Nullable<int> Last_Updt_Emp_No { get; set; }
        public Nullable<int> Last_Updt_Emp_Co_Cd { get; set; }
    }
}
