//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDW_COPY_vEMPLOYEE_INFO
    {
        public int Company_Cd { get; set; }
        public int Emp_No { get; set; }
        public string Social_Security_Number { get; set; }
        public string Name_Prefix { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_INITIAL { get; set; }
        public string LAST_NAME { get; set; }
        public string Name_Suffix { get; set; }
        public string JOB_RATE_CD { get; set; }
        public string FT_PT_Cd { get; set; }
        public string Regular_Temporary { get; set; }
        public Nullable<decimal> Standard_Hours { get; set; }
        public string UNION_MNGT_CD { get; set; }
        public string UNION_CD { get; set; }
        public Nullable<short> ENTERPRISE_CD { get; set; }
        public Nullable<short> BUSINESS_UNIT_CD { get; set; }
        public Nullable<short> VP_CD { get; set; }
        public Nullable<short> ORG_CD { get; set; }
        public Nullable<short> DEPT_CD { get; set; }
        public Nullable<short> SECT_CD { get; set; }
        public string Dept_Id { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public Nullable<System.DateTime> ADJ_HIRE_DATE { get; set; }
        public Nullable<System.DateTime> Seniority_Date { get; set; }
        public Nullable<short> Seniority_Number { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public Nullable<System.DateTime> DEATH_DATE { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public string JOB_STATUS_CD { get; set; }
        public Nullable<System.DateTime> JOB_STATUS_DATE { get; set; }
        public string WORK_STATUS { get; set; }
        public string JOB_SUFFIX { get; set; }
        public string WORK_MDS_LOCATION { get; set; }
        public string Home_Country { get; set; }
        public string HOME_ADDRESS1 { get; set; }
        public string HOME_ADDRESS2 { get; set; }
        public string HOME_CITY { get; set; }
        public string HOME_STATE { get; set; }
        public string HOME_ZIP { get; set; }
        public string TELEPHONE_OFFICE1 { get; set; }
        public string TELEPHONE_HOME { get; set; }
        public Nullable<int> SUPERVISOR_EMP_NO { get; set; }
        public Nullable<int> SUPERVISOR_COMPANY_CD { get; set; }
        public string PRIMARY_WINDOWS_NT_ACCOUNT { get; set; }
        public string EMAIL_ADDRESS_COMPANY { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<int> LAST_UPDATED_BY_COMPANY { get; set; }
        public Nullable<System.DateTime> Last_Updt_Ts { get; set; }
        public string Last_Updt_Usr_Id { get; set; }
        public Nullable<int> Last_Updt_Emp_No { get; set; }
        public Nullable<int> Last_Updt_Emp_Co_Cd { get; set; }
        public string JobTitle { get; set; }
    }
}
