//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Audit_Goal
    {
        public long AuditGoal_ID { get; set; }
        public Nullable<long> Goal_ID { get; set; }
        public Nullable<int> GoalFrequency_ID { get; set; }
        public Nullable<int> GoalLevel_ID { get; set; }
        public Nullable<int> Observer_ID { get; set; }
        public Nullable<int> MajorGroup_ID { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public Nullable<int> Sect_Id { get; set; }
        public Nullable<int> GoalYear { get; set; }
        public Nullable<int> GoalMonth { get; set; }
        public Nullable<double> GoalValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual T_JSSE_Goal T_JSSE_Goal { get; set; }
    }
}
