//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Audit_Category
    {
        public int AuditCategory_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public string Category { get; set; }
        public string CategoryDesc { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual T_JSSE_Master_Category T_JSSE_Master_Category { get; set; }
    }
}
