//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Hierarchy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_JSSE_Hierarchy()
        {
            this.T_JSSE_Observee = new HashSet<T_JSSE_Observee>();
            this.T_JSSE_Observer = new HashSet<T_JSSE_Observer>();
        }
    
        public int Hierarchy_ID { get; set; }
        public Nullable<int> MajorGroup_Id { get; set; }
        public string MajorGroup { get; set; }
        public Nullable<int> Org_Id { get; set; }
        public string Organization { get; set; }
        public Nullable<int> Dept_Id { get; set; }
        public string Department { get; set; }
        public Nullable<int> Sect_Id { get; set; }
        public string Section { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Observee> T_JSSE_Observee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Observer> T_JSSE_Observer { get; set; }
    }
}
