//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Report_Subscription
    {
        public int ReportSubscription_ID { get; set; }
        public Nullable<int> SaveTemplate_ID { get; set; }
        public string FileType { get; set; }
        public string DeliveryType { get; set; }
        public string ScheduleType { get; set; }
        public string Email { get; set; }
        public string User_Id { get; set; }
        public string DeliveryLocation { get; set; }
        public string ScheduleXMLforSSRS { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
