//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Security_UserGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_JSSE_Security_UserGroup()
        {
            this.T_JSSE_Audit_Security = new HashSet<T_JSSE_Audit_Security>();
        }
    
        public int SecurityUserGroup_ID { get; set; }
        public Nullable<int> SecurityGroup_ID { get; set; }
        public Nullable<int> SecurityUser_ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Audit_Security> T_JSSE_Audit_Security { get; set; }
        public virtual T_JSSE_Security_Group T_JSSE_Security_Group { get; set; }
        public virtual T_JSSE_Security_User T_JSSE_Security_User { get; set; }
    }
}
