//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Audit_CategoryBehavior_Map
    {
        public int AuditCategoryBehavior_MapID { get; set; }
        public Nullable<int> CategoryBehavior_MapID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> Behavior_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual T_JSSE_Master_CategoryBehavior_Map T_JSSE_Master_CategoryBehavior_Map { get; set; }
    }
}
