//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Main
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_JSSE_Main()
        {
            this.T_JSSE_Attachments = new HashSet<T_JSSE_Attachments>();
            this.T_JSSE_Category = new HashSet<T_JSSE_Category>();
            this.T_JSSE_Observee = new HashSet<T_JSSE_Observee>();
            this.T_JSSE_Observer = new HashSet<T_JSSE_Observer>();
        }
    
        public long JSSE_ID { get; set; }
        public string JobName { get; set; }
        public string JobDescription { get; set; }
        public Nullable<bool> IsAnonymous { get; set; }
        public Nullable<bool> IsExternal { get; set; }
        public string Status { get; set; }
        public Nullable<int> Region_ID { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> JSSEDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Attachments> T_JSSE_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Category> T_JSSE_Category { get; set; }
        public virtual T_JSSE_Master_Region T_JSSE_Master_Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Observee> T_JSSE_Observee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Observer> T_JSSE_Observer { get; set; }
    }
}
