//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_EDW_EmpInfo_Sync
    {
        public int Company_Cd { get; set; }
        public int Emp_No { get; set; }
        public string First_Name { get; set; }
        public string Middle_Initial { get; set; }
        public string Last_Name { get; set; }
        public string Name_Suffix { get; set; }
        public Nullable<short> Vp_Cd { get; set; }
        public Nullable<short> Org_Cd { get; set; }
        public Nullable<short> Dept_Cd { get; set; }
        public Nullable<short> Sect_Cd { get; set; }
        public Nullable<short> Active { get; set; }
        public Nullable<int> Supervisor_Emp_No { get; set; }
        public Nullable<int> Supervisor_Company_Cd { get; set; }
        public string Primary_Windows_NT_Account { get; set; }
        public string Email_Address_Company { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
    }
}
