//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Audit_Behavior
    {
        public int AuditBehavior_ID { get; set; }
        public Nullable<int> Behavior_ID { get; set; }
        public string Behavior { get; set; }
        public string BehaviorDesc { get; set; }
        public Nullable<int> MajorGroup_ID { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<int> BehaviorType_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual T_JSSE_Master_Behavior T_JSSE_Master_Behavior { get; set; }
    }
}
