//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Goal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_JSSE_Goal()
        {
            this.T_JSSE_Audit_Goal = new HashSet<T_JSSE_Audit_Goal>();
        }
    
        public long Goal_ID { get; set; }
        public Nullable<int> GoalFrequency_ID { get; set; }
        public Nullable<int> GoalLevel_ID { get; set; }
        public Nullable<int> Observer_ID { get; set; }
        public Nullable<int> MajorGroup_ID { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public Nullable<int> Sect_Id { get; set; }
        public Nullable<int> GoalYear { get; set; }
        public Nullable<int> GoalMonth { get; set; }
        public Nullable<double> GoalValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Audit_Goal> T_JSSE_Audit_Goal { get; set; }
        public virtual T_JSSE_Goal_Frequency T_JSSE_Goal_Frequency { get; set; }
        public virtual T_JSSE_Goal_Level T_JSSE_Goal_Level { get; set; }
        public virtual T_JSSE_Observer T_JSSE_Observer { get; set; }
    }
}
