//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Audit_Security
    {
        public int AuditSecurity_ID { get; set; }
        public Nullable<int> SecurityGroupPermission_ID { get; set; }
        public Nullable<int> SecurityUser_ID { get; set; }
        public Nullable<int> SecurityUserGroup_ID { get; set; }
        public Nullable<int> SecurityGroup_ID { get; set; }
        public Nullable<int> SecurityPermission_ID { get; set; }
        public Nullable<int> SecurityLevel_ID { get; set; }
        public string SecurityLevel { get; set; }
        public string GroupName { get; set; }
        public string PermissionName { get; set; }
        public Nullable<int> MajorGroup_ID { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string User_Id { get; set; }
        public string Email { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual T_JSSE_Security_GroupPermission T_JSSE_Security_GroupPermission { get; set; }
        public virtual T_JSSE_Security_UserGroup T_JSSE_Security_UserGroup { get; set; }
    }
}
