//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_JSSE_Category()
        {
            this.T_JSSE_Behavior = new HashSet<T_JSSE_Behavior>();
            this.T_JSSE_Comment = new HashSet<T_JSSE_Comment>();
        }
    
        public int JSSECategory_ID { get; set; }
        public Nullable<long> JSSE_ID { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public Nullable<int> Rating_ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Behavior> T_JSSE_Behavior { get; set; }
        public virtual T_JSSE_Main T_JSSE_Main { get; set; }
        public virtual T_JSSE_Master_Category T_JSSE_Master_Category { get; set; }
        public virtual T_JSSE_Master_Rating T_JSSE_Master_Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Comment> T_JSSE_Comment { get; set; }
    }
}
