//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Observer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_JSSE_Observer()
        {
            this.T_JSSE_Goal = new HashSet<T_JSSE_Goal>();
        }
    
        public int Observer_ID { get; set; }
        public Nullable<int> Hierarchy_ID { get; set; }
        public Nullable<long> JSSE_ID { get; set; }
        public Nullable<long> Emp_ID { get; set; }
        public string User_Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public string UserRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Goal> T_JSSE_Goal { get; set; }
        public virtual T_JSSE_Hierarchy T_JSSE_Hierarchy { get; set; }
        public virtual T_JSSE_Main T_JSSE_Main { get; set; }
    }
}
