//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Observee
    {
        public int Observee_ID { get; set; }
        public Nullable<long> JSSE_ID { get; set; }
        public Nullable<int> Hierarchy_ID { get; set; }
        public Nullable<long> Emp_ID { get; set; }
        public string User_Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual T_JSSE_Hierarchy T_JSSE_Hierarchy { get; set; }
        public virtual T_JSSE_Main T_JSSE_Main { get; set; }
    }
}
