//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Security_Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_JSSE_Security_Permission()
        {
            this.T_JSSE_Security_GroupPermission = new HashSet<T_JSSE_Security_GroupPermission>();
        }
    
        public int SecurityPermission_ID { get; set; }
        public string PermissionName { get; set; }
        public string PermissionDesc { get; set; }
        public Nullable<int> SecurityLevel_ID { get; set; }
        public string AppModule { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Security_GroupPermission> T_JSSE_Security_GroupPermission { get; set; }
        public virtual T_JSSE_Security_Level T_JSSE_Security_Level { get; set; }
    }
}
