//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_JSSE_Master_Behavior
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_JSSE_Master_Behavior()
        {
            this.T_JSSE_Audit_Behavior = new HashSet<T_JSSE_Audit_Behavior>();
            this.T_JSSE_Behavior = new HashSet<T_JSSE_Behavior>();
            this.T_JSSE_Master_CategoryBehavior_Map = new HashSet<T_JSSE_Master_CategoryBehavior_Map>();
        }
    
        public int Behavior_ID { get; set; }
        public string Behavior { get; set; }
        public string BehaviorDesc { get; set; }
        public Nullable<int> MajorGroup_ID { get; set; }
        public Nullable<int> Org_ID { get; set; }
        public Nullable<int> BehaviorType_ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Audit_Behavior> T_JSSE_Audit_Behavior { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Behavior> T_JSSE_Behavior { get; set; }
        public virtual T_JSSE_Master_BehaviorType T_JSSE_Master_BehaviorType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_JSSE_Master_CategoryBehavior_Map> T_JSSE_Master_CategoryBehavior_Map { get; set; }
    }
}
