//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConEdison.EHSApps.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_JSSE_GetSecurityGroups
    {
        public int SecurityGroup_ID { get; set; }
        public string GroupName { get; set; }
        public string GroupDesc { get; set; }
        public string MajorGroup_Id { get; set; }
        public string Org_Id { get; set; }
        public Nullable<int> Level_ID { get; set; }
        public string LevelName { get; set; }
        public string PermIDList { get; set; }
        public string PermList { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
